#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May 15 05:46:47 2019

@author: rebeccawang
"""

import pandas as pd

#data = pd.read_excel("pd_exm1.xlsx", None)

#print(data.keys())

#for sh_name in data.keys():
#    print("sheet name is : ", sh_name)
#    sh_data = pd.DataFrame(pd.read_excel("pd_exm1.xlsx",sh_name))
#    print(sh_data)
#    

data = pd.DataFrame(pd.read_excel("pd_exm1.xlsx"))
print(data.index)
print(data.columns)
print(data['姓名'])
print(data.loc[0])
print(data.loc[1])

print(data['分数'])

#还是没有解决 查找特定内容的问题